/* Populate SUPPLIER */
insert into SUPPLIER (Supplier_name, Supplier_cell, Supplier_email) values ('Cronin Inc', '0217667215', 'stichelaar0@businessweek.com');
insert into SUPPLIER (Supplier_name, Supplier_cell, Supplier_email) values ('Stanton, Wyman and Renner', '0836650898', 'obraunes1@spotify.com');
insert into SUPPLIER (Supplier_name, Supplier_cell, Supplier_email) values ('Murphy-Hegmann', '0735948469', 'mkillingbeck2@independent.co.uk');
insert into SUPPLIER (Supplier_name, Supplier_cell, Supplier_email) values ('Beatty Group', '0822385080', 'jchippindale3@ucsd.edu');
insert into SUPPLIER (Supplier_name, Supplier_cell, Supplier_email) values ('Roob and Sons', '0709049557', 'mnials4@printfriendly.com');
insert into SUPPLIER (Supplier_name, Supplier_cell, Supplier_email) values ('Trantow-Emmerich', '0050695496', 'sgrcic5@moonfruit.com');
insert into SUPPLIER (Supplier_name, Supplier_cell, Supplier_email) values ('Weissnat Group', '0904888513', 'wmclennan6@blogger.com');
insert into SUPPLIER (Supplier_name, Supplier_cell, Supplier_email) values ('Mills, Rodriguez and Collins', '0592110210', 'dadrienne7@apple.com');
insert into SUPPLIER (Supplier_name, Supplier_cell, Supplier_email) values ('VonRueden-Turner', '0109230634', 'sharyngton8@hibu.com');
insert into SUPPLIER (Supplier_name, Supplier_cell, Supplier_email) values ('Abernathy, Dietrich and Berge', '0112359266', 'kbrightling9@state.tx.us');
insert into SUPPLIER (Supplier_name, Supplier_cell, Supplier_email) values ('Cartwright, Johnson and Schroeder', '0158838645', 'nlomasnya@fotki.com');
insert into SUPPLIER (Supplier_name, Supplier_cell, Supplier_email) values ('O''Hara LLC', '0617177838', 'wcaustickb@earthlink.net');
insert into SUPPLIER (Supplier_name, Supplier_cell, Supplier_email) values ('Kihn and Sons', '0919977611', 'pkerryc@dailymotion.com');
insert into SUPPLIER (Supplier_name, Supplier_cell, Supplier_email) values ('Johns-Murphy', '0732501413', 'hcozinsd@slate.com');
insert into SUPPLIER (Supplier_name, Supplier_cell, Supplier_email) values ('Jacobi Inc', '0335362867', 'gboleyne@reverbnation.com');
insert into SUPPLIER (Supplier_name, Supplier_cell, Supplier_email) values ('Mohr, Simonis and Cummerata', '0697593754', 'lslatenf@si.edu');
insert into SUPPLIER (Supplier_name, Supplier_cell, Supplier_email) values ('Schamberger-Wiza', '0012513664', 'mpeapleg@dailymail.co.uk');
insert into SUPPLIER (Supplier_name, Supplier_cell, Supplier_email) values ('Koelpin Inc', '0630484688', 'bthoriush@yale.edu');
insert into SUPPLIER (Supplier_name, Supplier_cell, Supplier_email) values ('Ullrich, Renner and Terry', '0656369116', 'scaseroi@twitter.com');
insert into SUPPLIER (Supplier_name, Supplier_cell, Supplier_email) values ('Watsica LLC', '0786913020', 'ecaustonj@google.pl');
go

/* Populate PRODUCT */
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Mushroom - Morel Frozen', 26.46, 1);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Turkey - Breast, Double', 22.36, 20);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Bag - Bread, White, Plain', 45.04, 4);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Corn - Mini', 37.89, 21);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Brownies - Two Bite, Chocolate', 34.22, 7);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Table Cloth 81x81 Colour', 39.29, 17);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Maintenance Removal Charge', 25.46, 4);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Yeast - Fresh, Fleischman', 23.09, 9);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Placemat - Scallop, White', 30.52, 2);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Waffle Stix', 47.63, 41);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Pineapple - Regular', 41.82, 3);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Olives - Morracan Dired', 49.83, 19);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Beer - Moosehead', 32.65, 25);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Langers - Mango Nectar', 49.97, 15);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Lettuce - Boston Bib', 28.17, 19);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Cheese - Brie Roitelet', 48.4, 49);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Soup - Campbells, Creamy', 45.31, 40);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Cake - Mini Potato Pancake', 44.27, 30);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Banana', 25.71, 48);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Coconut - Shredded, Sweet', 46.03, 6);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Veal Inside - Provimi', 37.04, 5);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Wine - Magnotta - Cab Sauv', 28.12, 1);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Veal - Leg, Provimi - 50 Lb Max', 26.79, 25);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Pike - Frozen Fillet', 37.6, 40);
insert into PRODUCT (Description, Sell_price, Quantity_in_stock) values ('Ocean Spray - Kiwi Strawberry', 36.62, 49);
go

/* Populate SALES_ORDER */
insert into SALES_ORDER (Sales_date) values ('2022/01/20');
insert into SALES_ORDER (Sales_date) values ('2022/03/01');
insert into SALES_ORDER (Sales_date) values ('2022/03/22');
insert into SALES_ORDER (Sales_date) values ('2022/03/04');
insert into SALES_ORDER (Sales_date) values ('2022/03/08');
insert into SALES_ORDER (Sales_date) values ('2022/02/11');
insert into SALES_ORDER (Sales_date) values ('2022/02/02');
insert into SALES_ORDER (Sales_date) values ('2022/01/11');
insert into SALES_ORDER (Sales_date) values ('2022/02/16');
insert into SALES_ORDER (Sales_date) values ('2022/03/11');
insert into SALES_ORDER (Sales_date) values ('2022/02/06');
insert into SALES_ORDER (Sales_date) values ('2022/02/05');
insert into SALES_ORDER (Sales_date) values ('2022/01/29');
insert into SALES_ORDER (Sales_date) values ('2022/01/24');
insert into SALES_ORDER (Sales_date) values ('2022/01/01');
insert into SALES_ORDER (Sales_date) values ('2022/03/04');
insert into SALES_ORDER (Sales_date) values ('2022/02/28');
insert into SALES_ORDER (Sales_date) values ('2022/01/26');
insert into SALES_ORDER (Sales_date) values ('2022/01/16');
insert into SALES_ORDER (Sales_date) values ('2022/03/04');
insert into SALES_ORDER (Sales_date) values ('2022/02/04');
insert into SALES_ORDER (Sales_date) values ('2022/01/03');
insert into SALES_ORDER (Sales_date) values ('2022/01/03');
insert into SALES_ORDER (Sales_date) values ('2022/03/20');
insert into SALES_ORDER (Sales_date) values ('2022/01/28');
insert into SALES_ORDER (Sales_date) values ('2022/01/07');
insert into SALES_ORDER (Sales_date) values ('2022/02/05');
insert into SALES_ORDER (Sales_date) values ('2022/02/20');
insert into SALES_ORDER (Sales_date) values ('2022/03/20');
insert into SALES_ORDER (Sales_date) values ('2022/01/03');
insert into SALES_ORDER (Sales_date) values ('2022/01/31');
insert into SALES_ORDER (Sales_date) values ('2022/01/17');
insert into SALES_ORDER (Sales_date) values ('2022/01/02');
insert into SALES_ORDER (Sales_date) values ('2022/01/12');
insert into SALES_ORDER (Sales_date) values ('2022/01/28');
insert into SALES_ORDER (Sales_date) values ('2022/01/23');
insert into SALES_ORDER (Sales_date) values ('2022/02/06');
insert into SALES_ORDER (Sales_date) values ('2022/01/03');
insert into SALES_ORDER (Sales_date) values ('2022/01/20');
insert into SALES_ORDER (Sales_date) values ('2022/01/07');
insert into SALES_ORDER (Sales_date) values ('2022/02/12');
insert into SALES_ORDER (Sales_date) values ('2022/03/08');
insert into SALES_ORDER (Sales_date) values ('2022/01/05');
insert into SALES_ORDER (Sales_date) values ('2022/02/20');
insert into SALES_ORDER (Sales_date) values ('2022/01/09');
insert into SALES_ORDER (Sales_date) values ('2022/02/13');
insert into SALES_ORDER (Sales_date) values ('2022/02/20');
insert into SALES_ORDER (Sales_date) values ('2022/01/29');
insert into SALES_ORDER (Sales_date) values ('2022/02/08');
insert into SALES_ORDER (Sales_date) values ('2022/03/28');
insert into SALES_ORDER (Sales_date) values ('2022/01/01');
insert into SALES_ORDER (Sales_date) values ('2022/01/06');
insert into SALES_ORDER (Sales_date) values ('2022/03/25');
insert into SALES_ORDER (Sales_date) values ('2022/03/12');
insert into SALES_ORDER (Sales_date) values ('2022/01/10');
insert into SALES_ORDER (Sales_date) values ('2022/01/30');
insert into SALES_ORDER (Sales_date) values ('2022/03/05');
insert into SALES_ORDER (Sales_date) values ('2022/03/08');
insert into SALES_ORDER (Sales_date) values ('2022/03/24');
insert into SALES_ORDER (Sales_date) values ('2022/01/08');
insert into SALES_ORDER (Sales_date) values ('2022/03/10');
insert into SALES_ORDER (Sales_date) values ('2022/03/14');
insert into SALES_ORDER (Sales_date) values ('2022/03/20');
insert into SALES_ORDER (Sales_date) values ('2022/03/17');
insert into SALES_ORDER (Sales_date) values ('2022/03/18');
insert into SALES_ORDER (Sales_date) values ('2022/03/17');
insert into SALES_ORDER (Sales_date) values ('2022/01/19');
insert into SALES_ORDER (Sales_date) values ('2022/02/19');
insert into SALES_ORDER (Sales_date) values ('2022/03/20');
insert into SALES_ORDER (Sales_date) values ('2022/01/13');
insert into SALES_ORDER (Sales_date) values ('2022/03/26');
insert into SALES_ORDER (Sales_date) values ('2022/01/26');
insert into SALES_ORDER (Sales_date) values ('2022/03/04');
insert into SALES_ORDER (Sales_date) values ('2022/01/20');
insert into SALES_ORDER (Sales_date) values ('2022/01/06');
insert into SALES_ORDER (Sales_date) values ('2022/01/05');
insert into SALES_ORDER (Sales_date) values ('2022/03/10');
insert into SALES_ORDER (Sales_date) values ('2022/01/15');
insert into SALES_ORDER (Sales_date) values ('2022/03/04');
insert into SALES_ORDER (Sales_date) values ('2022/03/28');
insert into SALES_ORDER (Sales_date) values ('2022/01/20');
insert into SALES_ORDER (Sales_date) values ('2022/03/17');
insert into SALES_ORDER (Sales_date) values ('2022/03/21');
insert into SALES_ORDER (Sales_date) values ('2022/02/14');
insert into SALES_ORDER (Sales_date) values ('2022/03/24');
insert into SALES_ORDER (Sales_date) values ('2022/03/01');
insert into SALES_ORDER (Sales_date) values ('2022/02/24');
insert into SALES_ORDER (Sales_date) values ('2022/03/10');
insert into SALES_ORDER (Sales_date) values ('2022/01/19');
insert into SALES_ORDER (Sales_date) values ('2022/02/24');
go

/* Populate PURCHASE_ORDER */
insert into PURCHASE_ORDER (Supplier_ID, Purchase_date) values (6, '2022/03/17');
insert into PURCHASE_ORDER (Supplier_ID, Purchase_date) values (9, '2022/02/03');
insert into PURCHASE_ORDER (Supplier_ID, Purchase_date) values (20, '2022/01/31');
insert into PURCHASE_ORDER (Supplier_ID, Purchase_date) values (20, '2022/03/22');
insert into PURCHASE_ORDER (Supplier_ID, Purchase_date) values (17, '2022/01/09');
insert into PURCHASE_ORDER (Supplier_ID, Purchase_date) values (10, '2022/01/30');
insert into PURCHASE_ORDER (Supplier_ID, Purchase_date) values (4, '2022/01/15');
insert into PURCHASE_ORDER (Supplier_ID, Purchase_date) values (5, '2022/01/31');
insert into PURCHASE_ORDER (Supplier_ID, Purchase_date) values (18, '2022/01/23');
insert into PURCHASE_ORDER (Supplier_ID, Purchase_date) values (4, '2022/01/13');
insert into PURCHASE_ORDER (Supplier_ID, Purchase_date) values (17, '2022/03/15');
insert into PURCHASE_ORDER (Supplier_ID, Purchase_date) values (17, '2022/03/03');
go

/* Populate PURCHASE_ORDER_ITEM */
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (10, 12, 4, 32.91);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (12, 1, 3, 45.22);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (8, 21, 17, 38.79);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (3, 16, 17, 44.53);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (4, 23, 8, 24.78);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (11, 23, 3, 47.23);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (2, 10, 12, 34.8);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (8, 13, 9, 32.15);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (10, 5, 4, 49.14);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (7, 15, 20, 25.33);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (8, 5, 8, 49.14);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (11, 24, 17, 30.93);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (9, 9, 4, 22.13);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (6, 23, 3, 23.05);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (7, 18, 18, 37.45);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (9, 3, 19, 39.61);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (10, 7, 4, 33.04);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (2, 22, 8, 36.92);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (2, 17, 20, 46.12);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (2, 21, 8, 29.52);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (8, 9, 16, 26.78);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (8, 4, 13, 33.18);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (4, 11, 3, 20.45);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (7, 16, 18, 41.19);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (10, 11, 13, 21.08);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (10, 11, 9, 35.79);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (5, 13, 2, 44.16);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (11, 19, 3, 36.06);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (10, 21, 20, 27.09);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (3, 21, 6, 31.94);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (6, 10, 18, 20.64);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (5, 1, 10, 29.75);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (2, 12, 5, 42.45);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (5, 25, 16, 36.01);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (10, 6, 20, 39.59);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (9, 13, 5, 35.37);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (5, 8, 16, 27.3);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (7, 18, 17, 31.64);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (11, 5, 6, 22.09);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (1, 19, 20, 44.93);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (3, 15, 10, 21.88);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (5, 7, 4, 20.74);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (1, 15, 17, 36.16);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (11, 2, 6, 29.84);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (12, 19, 4, 27.58);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (6, 13, 4, 20.18);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (4, 8, 18, 46.49);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (2, 10, 16, 43.66);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (10, 20, 14, 38.03);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (7, 19, 5, 38.83);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (6, 21, 10, 28.28);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (7, 23, 18, 41.36);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (5, 21, 19, 29.54);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (8, 2, 6, 28.52);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (2, 23, 9, 46.93);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (8, 6, 10, 49.46);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (10, 24, 15, 37.35);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (10, 4, 1, 46.6);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (9, 7, 2, 37.16);
insert into PURCHASE_ORDER_ITEM (Purchase_ID, Product_ID , Quantity_purchased, Cost_price) values (3, 23, 15, 25.25);
go

/* Populate SALES_ORDER_ITEM */
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (27, 25, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (15, 15, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (34, 8, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (7, 17, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (54, 2, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (36, 23, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (18, 7, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (77, 5, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (19, 1, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (68, 21, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (85, 20, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (4, 11, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (68, 14, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (86, 10, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (67, 5, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (60, 1, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (63, 16, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (30, 11, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (44, 8, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (2, 13, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (41, 9, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (10, 14, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (30, 16, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (14, 1, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (66, 21, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (47, 6, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (89, 12, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (25, 7, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (77, 13, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (69, 16, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (29, 14, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (22, 9, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (80, 12, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (18, 10, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (40, 1, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (43, 10, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (14, 25, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (12, 11, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (63, 16, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (55, 5, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (25, 12, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (90, 5, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (38, 17, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (33, 22, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (62, 24, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (11, 13, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (62, 23, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (84, 5, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (12, 13, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (8, 16, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (26, 6, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (38, 8, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (46, 20, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (47, 4, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (53, 20, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (66, 19, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (79, 2, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (2, 20, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (76, 13, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (2, 18, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (59, 20, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (15, 2, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (87, 15, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (14, 3, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (68, 9, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (26, 7, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (40, 8, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (24, 2, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (39, 6, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (31, 2, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (70, 7, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (55, 9, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (76, 24, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (50, 7, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (86, 20, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (27, 24, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (15, 24, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (8, 6, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (78, 15, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (89, 15, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (3, 13, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (88, 23, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (39, 17, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (34, 4, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (47, 3, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (34, 6, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (1, 6, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (71, 4, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (75, 23, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (67, 12, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (59, 9, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (13, 15, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (30, 1, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (45, 18, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (11, 23, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (30, 8, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (48, 15, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (55, 11, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (13, 4, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (89, 3, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (26, 17, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (6, 22, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (64, 25, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (42, 12, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (11, 24, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (25, 6, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (38, 21, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (18, 14, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (44, 10, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (65, 16, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (7, 25, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (74, 3, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (77, 12, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (14, 16, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (77, 23, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (73, 9, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (89, 13, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (31, 14, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (5, 18, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (15, 9, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (73, 8, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (10, 17, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (43, 8, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (38, 22, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (82, 18, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (16, 23, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (58, 3, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (76, 1, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (33, 17, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (25, 6, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (18, 9, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (33, 15, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (86, 5, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (70, 3, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (41, 19, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (37, 19, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (2, 17, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (74, 21, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (22, 10, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (6, 9, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (86, 8, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (47, 3, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (33, 4, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (3, 2, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (64, 16, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (20, 25, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (13, 23, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (74, 13, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (31, 8, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (22, 11, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (19, 11, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (69, 20, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (72, 14, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (44, 8, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (69, 22, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (8, 20, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (9, 20, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (57, 5, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (55, 8, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (49, 18, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (24, 14, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (46, 6, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (29, 2, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (61, 7, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (56, 14, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (50, 19, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (3, 2, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (64, 10, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (56, 22, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (81, 3, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (13, 9, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (73, 6, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (39, 1, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (60, 4, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (54, 25, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (52, 14, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (68, 11, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (3, 6, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (17, 18, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (1, 25, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (47, 7, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (38, 15, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (16, 25, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (89, 19, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (66, 3, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (67, 23, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (52, 3, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (35, 22, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (20, 11, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (79, 6, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (9, 11, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (76, 4, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (27, 14, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (43, 1, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (80, 18, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (65, 20, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (74, 5, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (79, 5, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (30, 13, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (5, 16, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (31, 1, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (73, 15, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (20, 23, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (66, 15, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (44, 9, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (7, 24, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (71, 16, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (32, 11, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (38, 12, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (89, 18, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (23, 5, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (78, 19, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (81, 17, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (60, 8, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (81, 9, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (78, 15, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (18, 1, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (69, 11, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (18, 17, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (71, 6, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (48, 9, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (67, 11, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (7, 4, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (17, 12, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (23, 22, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (33, 14, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (7, 16, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (79, 9, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (47, 25, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (35, 24, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (9, 6, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (46, 17, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (78, 24, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (37, 19, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (23, 15, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (78, 16, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (11, 24, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (10, 2, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (38, 3, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (56, 20, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (39, 8, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (82, 18, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (85, 16, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (20, 2, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (11, 19, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (49, 8, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (50, 8, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (5, 9, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (81, 18, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (84, 1, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (53, 8, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (40, 20, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (1, 10, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (39, 20, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (30, 6, 1);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (64, 20, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (6, 5, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (9, 17, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (77, 20, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (53, 12, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (45, 24, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (33, 4, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (72, 22, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (61, 16, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (42, 13, 3);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (7, 20, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (56, 1, 4);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (27, 2, 2);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (17, 22, 5);
insert into SALES_ORDER_ITEM (Sales_ID , Product_ID , Quantity_sold) values (35, 5, 1);
go